name: "fublog-development"

services:

  postgres-dev:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
      args:
        language: de_DE
    environment:
      POSTGRES_USER: "fublog"
      POSTGRES_PASSWORD: "8!06"
      POSTGRES_DB: "fublog"
    ports:
      - "5020:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "5041:1025"  # SMTP port
      - "5040:8025" # HTTP port
